name: smart_date_field_picker
description: Customizable Flutter date picker with calendar overlay, keyboard navigation, dynamic ranges, and appearance customization.
homepage: https://github.com/sumit-home2904/smart_date_field_picker/tree/main/example
repository: https://github.com/sumit-home2904/smart_date_field_picker
issue_tracker: https://github.com/sumit-home2904/smart_date_field_picker/issues
Publisher: Sumit Sharma
license: MIT

version: 0.0.3+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
